name: Check PR
on:
  pull_request:
    paths:
      - 'src/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  summary:
    name: Check summary
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl-full:latest
    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y findutils bash git
      - name: Checkout
        id: checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - name: Check summary
        run: res/ci/check-summary.sh
  format:
    name: Check formatting
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl-full:latest
    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y vmdfmt bash git
      - name: Checkout
        id: checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - name: Check formatting
        run: res/ci/format.sh
  linkcheck:
    name: Check links
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-musl-full:latest
    steps:
      - name: Prepare container
        run: |
          xbps-install -Syu || xbps-install -Syu xbps
          xbps-install -yu
          xbps-install -y mdbook-linkcheck bash git
      - name: Checkout
        id: checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - name: Check links
        run: res/ci/linkcheck.sh
  commits:
    name: Check commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: classabbyamp/treeless-checkout-action@v1
      - name: Check commit messages
        run: res/ci/commit-lint.sh
